//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalSocialWebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animals
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<int> RaceId { get; set; }
        public Nullable<System.DateTime> BirtOfDate { get; set; }
        public string OwnerId { get; set; }
    
        public virtual HealtyCertificate HealtyCertificate { get; set; }
        public virtual Race Race { get; set; }
    }
}
