//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalSocialWebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HealtyCertificate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HealtyCertificate()
        {
            this.VaccineHealtyCertificate = new HashSet<VaccineHealtyCertificate>();
        }
    
        public string Id { get; set; }
        public string Comment { get; set; }
    
        public virtual Animals Animals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaccineHealtyCertificate> VaccineHealtyCertificate { get; set; }
    }
}
