//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimalSocialWebApi.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vaccine
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vaccine()
        {
            this.VaccineHealtyCertificate = new HashSet<VaccineHealtyCertificate>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<int> FirstPractice { get; set; }
        public Nullable<int> Repetition { get; set; }
        public Nullable<decimal> YearlyRepetiton { get; set; }
        public string Comment { get; set; }
        public string VaccineType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaccineHealtyCertificate> VaccineHealtyCertificate { get; set; }
    }
}
